# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170928_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetRecord',
            new_name='ServerRecord',
        ),
    ]
