# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170929_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '错误日志表',
            },
        ),
        migrations.AlterField(
            model_name='memory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.CharField(max_length=128, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='内存SN号'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='speed',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_platform',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, max_length=128, verbose_name='SN号'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='server_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Server'),
        ),
    ]
